[package]
name = "x11oo"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
x11 = { version = "2.20.1", features = ["xlib"] }

[build-dependencies]
pkg-config = "0.3.24"

[features]
xfixes = []
